/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 magasin1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/magasin1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube013.geometry} material={materials['white vinyl']} />
      <mesh geometry={nodes.Cube013_1.geometry} material={materials.Cycles_Architectural_Glass} />
      <mesh geometry={nodes.Cube013_2.geometry} material={materials.grey} />
      <mesh geometry={nodes.Cube013_3.geometry} material={materials.stainless} />
      <mesh geometry={nodes.Cube013_4.geometry} material={materials['prah.002']} />
      <mesh geometry={nodes.Cube013_5.geometry} material={materials.black} />
      <mesh geometry={nodes.Cube013_6.geometry} material={materials['glass dvere']} />
      <mesh geometry={nodes.Cube013_7.geometry} material={nodes.Cube013_7.material} />
      <mesh geometry={nodes.Cube013_8.geometry} material={materials.metal} />
      <mesh geometry={nodes.Cube013_9.geometry} material={materials['Brick wall']} />
      <mesh geometry={nodes.Cube013_10.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Cube013_11.geometry} material={materials.mur} />
      <mesh geometry={nodes.Cube013_12.geometry} material={materials['Hanger_Bake Textures']} />
      <mesh geometry={nodes.Cube013_13.geometry} material={materials['Hanger_Bake Metal']} />
      <mesh geometry={nodes.Cube013_14.geometry} material={materials.jqueta_Lowpoly_20k} />
      <mesh geometry={nodes.Cube013_15.geometry} material={materials['bois foncé']} />
      <mesh geometry={nodes.Cube013_16.geometry} material={materials['bois clair']} />
      <mesh geometry={nodes.Cube013_17.geometry} material={materials.bois} />
      <mesh geometry={nodes.Cube013_18.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube013_19.geometry} material={materials.membrane} />
      <mesh geometry={nodes.Cube013_20.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.Cube013_21.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Cube013_22.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Cube013_23.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.Cube013_24.geometry} material={materials['Material.015']} />
      <mesh geometry={nodes.Cube013_25.geometry} material={materials['metal.001']} />
      <mesh geometry={nodes.Cube013_26.geometry} material={materials.book_encyclopedia_set_01_cover} />
      <mesh geometry={nodes.Cube013_27.geometry} material={materials.book_encyclopedia_set_01_paper} />
      <mesh geometry={nodes.Cube013_28.geometry} material={materials['pot.001']} />
      <mesh geometry={nodes.Cube013_29.geometry} material={materials['Material.017']} />
      <mesh geometry={nodes.Cube013_30.geometry} material={materials['plant.002']} />
      <mesh geometry={nodes.Cube013_31.geometry} material={materials['plant.003']} />
      <mesh geometry={nodes.Cube013_32.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube013_33.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube013_34.geometry} material={materials.fabric} />
      <mesh geometry={nodes.Cube013_35.geometry} material={materials['grungy metal']} />
      <mesh geometry={nodes.Cube013_36.geometry} material={materials['black matte']} />
      <mesh geometry={nodes.Cube013_37.geometry} material={materials['white matte']} />
      <mesh geometry={nodes.Cube013_38.geometry} material={materials['black glossy']} />
      <mesh geometry={nodes.Cube013_39.geometry} material={materials['pink plastik']} />
      <mesh geometry={nodes.Cube013_40.geometry} material={materials['dust cover']} />
      <mesh geometry={nodes.Cube013_41.geometry} material={materials['красный матовый']} />
      <mesh geometry={nodes.Cube013_42.geometry} material={materials.veneer} />
      <mesh geometry={nodes.Cube013_43.geometry} material={materials['veneer (side)']} />
      <mesh geometry={nodes.Cube013_44.geometry} material={materials['Old Copper (Copper)']} />
      <mesh geometry={nodes.Cube013_45.geometry} material={materials['White Marble']} />
      <mesh geometry={nodes.Cube013_46.geometry} material={materials['T-shirt_masterMAT']} />
      <mesh geometry={nodes.Cube013_47.geometry} material={materials.sweater} />
      <mesh geometry={nodes.Cube013_48.geometry} material={materials.soulvet} />
      <mesh geometry={nodes.Cube013_49.geometry} material={materials['Grey curtains']} />
    </group>
  )
}

useGLTF.preload('/models/magasin1.glb')
