/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/neon.glb 
*/

import React from 'react'
import {useGLTF} from '@react-three/drei'

export function Model(props) {
    const {nodes, materials} = useGLTF('/models/neon.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.BézierCircle.geometry}>
                <meshStandardMaterial
                    color="white"
                    emissive="#00f3ff"
                    emissiveIntensity={20}
                    toneMapped={false}
                />
            </mesh>
            <mesh geometry={nodes.BézierCurve003.geometry}>
                <meshStandardMaterial
                    color="white"
                    emissive="#8807ff"
                    emissiveIntensity={20}
                    toneMapped={false}
                />
            </mesh>
        </group>
    )
}

useGLTF.preload('/models/neon.glb')
