/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/tshirt.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tshirt.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Comfortable_T-Shirt'].geometry} material={materials['Material.001']} scale={3.788} />
    </group>
  )
}

useGLTF.preload('/tshirt.glb')
